server:
  port: 8080
client:
  url: http://62.109.21.174:9090
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6543/stats
    username: stat
    password: stat
