server:
  port: 8080
client:
  url: http://62.109.21.174:9090
spring:
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://62.109.21.174:5433/service
    username: service
    password: service
