server:
  port=8080
client:
  url=http://localhost:9090
spring:
  datasource:
    driverClassName=org.postgresql.Driver
    url=jdbc:postgresql://localhost:6642/main
    username=main
    password=main
