drop table IF EXISTS users, categories, locations, events;

create table if not exists users (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(255) NOT NULL,
email VARCHAR(512) NOT NULL UNIQUE
);

create table if not exists categories (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS locations (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	lat VARCHAR NOT NULL,
	lon VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	annotation VARCHAR NOT NULL,
	category INTEGER REFERENCES categories (id) ON DELETE RESTRICT,
	created_on TIMESTAMP,
	description VARCHAR NOT NULL,
	event_date TIMESTAMP,
	initiator BIGINT REFERENCES users (id) ON DELETE CASCADE,
	location BIGINT REFERENCES locations (id) ON DELETE CASCADE,
	paid BOOLEAN NOT NULL,
	participants_limit BIGINT,
	published_on TIMESTAMP,
	request_moderation BOOLEAN NOT NULL,
	state VARCHAR,
	title VARCHAR NOT NULL
);