server:
  port: 9090
client:
  url: http://62.109.21.174:9090
spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://62.109.21.174:6543/stats
    username: stat
    password: stat
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
  sql:
    init: mode=always
