server:
  port: 9090
client:
  url: http://localhost:9090
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6543/stats
    username: stat
    password: stat
